### ISSUE TITLE
Pluginlib on catkin

### ISSUE THREAD

**Issue by wmeeusse** [ros/pluginlib#1]
I'm using plugins in a pure catkin environment, where both the plugins and the code that calls the plugins is in catkin. When instantiating the plugin loader, I get the following (meaningless?) error:

[ERROR] [1351729666.226378607]: Could not find package name for class /home/wim/stacks/groovy/catkin_ws/src/joint_state_controller/joint_state_plugin.xml

What does this mean? The xml file is a class? Does it fail to find a package, or just the name of a package? I'm not sure what to make of this.

Browsing through the pluginlib code, I noticed it's still looking for a manifest.xml, which is pre-catkin. Is pluginlib tested in the pure catkin situation I'm working in?  

It would also be great if the error message could be much more meaningful, so I'd have some idea of what to fix.

**Comment by dirk-thomas** [comment]
already fixed in 75902291281d8aa9893614812e5152ce31207140

**Comment by mirzashah** [comment]
Actually the error message is misleading and has thrown me off a few times as I've taken over maintenance of pluginlib. When that error occurs, what's actually happening is that it can't find the file "manifest.xml" or "package.xml" at the same directory level as the plugin XML file so it can't be sure that it's actually a package. It'll keep trying to truck along without it but it gives you that misleading message on the way. However, Dirk is correct in that the new release should stop the problem from occuring all together.

I've patched the issue with a more meaningful error message (not released yet), so we can safely close this issue for now.

**Comment by wmeeusse** [comment]
Thanks Mirza, this is awesome feedback on the error message!

As for the bug itself, I was running with the debian in shadow fixed that got built and pushed this afternoon, while the bug got fixed 5 days ago.  Was the original fix not yet released?  Now that I can understand the error message, I'll take another look at my setup.

**Comment by dirk-thomas** [comment]
The fix was released today as 1.9.3 (see 5678160b81760e309fc67cfd9f0a3ff77a1f9330)
