### ISSUE TITLE
Support for boost filesystem v2

### ISSUE THREAD

**Issue by marioprats** [ros/pluginlib#10]
Inside class_loader_imp.h there are a couple of calls specific to boost filesystem v3 that won't compile on projects using v2. There are just two of them: native() and filename().string(). We could use the macro BOOST_FILESYSTEM_VERSION to detect the version in use and then call the appropriate function. If this makes sense I can submit a pull request with the changes.

**Comment by mirzashah** [comment]
Yes please submit a pull request.
