### ISSUE TITLE
Load a class and pass arguments to the constructor [Question]

### ISSUE THREAD

**Issue by mayman99** [ros/pluginlib#127]
I've an architecture where I've the `plugins` has to have arguments passed to its constructors, 

sth like this ` AuthorPlugin::AuthorPlugin(QWidget* parent) : SetupAssistantWidget(parent)` and the `SetupAssistantWidget` is the interface, is there a way to do that with `pluginlib`?

**Comment by mikaelarguedas** [comment]
It is currently not possible to pass constructor arguments to plugins loaded by pluginlib (this is a restriction of `class_loader` the mechanism used for loading and instanciating the classes)

**Comment by caioaamaral** [comment]
you could initialize `Qwidget parent` inside `SetupAssistantWidget` by creating some initialize function that receives a Qwidget* as param. You could even override this function from your plugin implementation:

`AuthorPlugin::initialize(QWidget* parent) override;`

And then calling it just after default constructor of your plugin:

```
global Qwidget* parent;

AuthorPlugiin some_plugin;

some_plugiin.initialize(parent);
```

**Comment by clalancette** [comment]
Given that this is a very old question, I'm going to close this out.  Please feel free to reopen if you think there is something to change here.
