### ISSUE TITLE
ROS2 on Windows, #warning is not recognized by VS

### ISSUE THREAD

**Issue by brawner** [ros/pluginlib#136]
In this deprecated header: https://github.com/ros/pluginlib/blob/9b319f1440a7153d6edf68067093449ff7b14201/pluginlib/include/pluginlib/class_list_macros.h#L36

Possible solutions:

- Use ```#pragma message("...")```
- Surround ```#warning``` checking for compiler 
- Remove the deprecated header and break things

More discussion about solutions
https://stackoverflow.com/questions/2685598/warning-in-visual-studio

**Comment by clalancette** [comment]
I think we removed this a long time ago, so going ahead and closing this one.
