### ISSUE TITLE
Why keep both .h and .hpp headers at the same time?

### ISSUE THREAD

**Issue by kejxu** [ros/pluginlib#139]
Asking out of curiosity, why are we keeping both `.h` and `.hpp` header files at the same time?

**Comment by nuclearsandwich** [comment]
The headers were renamed in #70 with the intent do deprecate the `.h` headers and introduce a C API for ROS 2 in the future.

#115 removes the deprecation warning based on feedback received in https://github.com/ros/pluginlib/pull/70#issuecomment-379435585

When N-turtle comes around we'll have to determine if the warning should be reintroduced.

If this answers your question feel free to close the issue.
