### ISSUE TITLE
Errors building with XCode 11 on Mojave

### ISSUE THREAD

**Issue by nuclearsandwich** [ros/pluginlib#168]
Installing XCode from the app store currently brings XCode 11. However there is a long list of errors when building pluginlib with it on macOS Mojave. It's unclear from the error text whether upgrading to macOS 10.15 before using XCode 11 will be sufficient to resolve the issue and I don't have any Catalina machines to try on.

stderr log from a test build: https://gist.github.com/nuclearsandwich/307e2f33edf5ba4db2188443bcf39987

**Comment by clalancette** [comment]
I do believe that this is fixed by #212, so I'm going to close this out.  Feel free to reopen if I turn out to be wrong.
