### ISSUE TITLE
Use common FindTinyXML.cmake

### ISSUE THREAD

**Issue by wjwwood** [ros/pluginlib#18]
There is a new package called cmake_modules, which we just created:

https://github.com/ros/cmake_modules

It provides a common FindTinyXML.cmake CMake module, which we should all try to use in order to prevent issues when doing things like cross-compiling.

This is a low priority, but a good idea. The package is available for Hydro and Groovy, it will be in public on the next sync.

**Comment by mirzashah** [comment]
Ah good idea...I was just looking at the CMakeLists.txt file for pluginlib and was wondering how tinyxml got in there without a find_package. I guess it's already in the default path on ubuntu so no need for find_package or include_directories functions, just link against "tinyxml".
