### ISSUE TITLE
Inheritance chains

### ISSUE THREAD

**Issue by danepowell** [ros/pluginlib#19]
Should inheritance 'chains' be possible with plugins? i.e., Base Class > Derived Class 1 > Derived Class 2.

My problem: I want to build a plugin (rviz::OmniTool) that uses rviz::InteractionTool as a base. But rviz::InteractionTool is already derived from rviz::Tool. So the desired inheritance is rviz::Tool > rviz::InteractionTool > rviz::OmniTool.

The problem is that rviz::OmniTool doesn't show up in rviz, although it does get returned by rospack plugins, so pluginlib knows it exists. However, if I change it to be derived directly from rviz::Tool, it shows up just fine.

Does this sound like a problem with pluginlib or rviz?

**Comment by mirzashah** [comment]
@danepowell Ah, this is an interesting question! 

It's likely that rviz when loading plugins is looking for classes that have the interface rviz::Tool. Even though rviz::InteractionTool is an rviz::Tool, the plugin system does not know that unless you tell it explicitly through the PLUGINLIB_EXPORT_CLASS macro.  I'm betting the problem isn't you deriving from rviz::InteractionTool as it is with your PLUGINLIB_EXPORT_CLASS macro. So...
1) Derive from rviz::InteractionTool as you had desired
2) Make sure your PLUGINLIB_EXPORT_CLASS Macro looks like this this:
`PLUGINLIB_EXPORT_CLASS(rviz::OmniTool, rviz::Tool)`
Make sure that the second argument is rviz::Tool and NOT rviz::InteractionTool. 

Hopefully that was your issue and this resolves it. If not, just leave a comment.

Also note that if you want to register plugins that can be used through any interface in the hierarchy, you can use the PLUGINLIB_EXPORT_CLASS multiple times, each time for a different base. e.g.:

```
PLUGINLIB_EXPORT_CLASS(rviz::OmniTool, rviz::InteractionTool) 
PLUGINLIB_EXPORT_CLASS(rviz::OmniTool, rviz::Tool)
```

Oh also note that rospack plugin querying just looks at the plugin xml files that packages export. That's what the package promises, but it may not actually contain the plugins it promises at runtime.

**Comment by danepowell** [comment]
Awesome! That did the trick. Maybe it's worth mentioning the multiple-PLUGINLIB_EXPORT_CLASS trick on the wiki page?

**Comment by mirzashah** [comment]
Good idea, will do that now.
