### ISSUE TITLE
For non-use of ros dependency

### ISSUE THREAD

**Issue by jim1949** [ros/pluginlib#195]
Hi, our developers are using pluginlib now, but it is always difficult to transfer from ROS to ROS2 or other communication tools, so my question is that is it possible for us not to use pluginlib without using ROS?

**Comment by clalancette** [comment]
In short: not really.  This package depends on several ROS-specific headers and functionality (most notably `class_loader`, `ros/console.h`, and `ros/package.h`).  The ROS 2 version has far fewer dependencies (only `class_loader`, as far as I can tell).  In theory it should be possible to replace those with custom implementations, but we don't have anything to do that right now.

I'm going to close this out.  In the future, please ask questions like this on https://answers.ros.org, which is our central place for questions and answers.
