### ISSUE TITLE
no implementation for QNX filesystem lib in CMakeLists.txt

### ISSUE THREAD

**Issue by asobhy-qnx** [ros/pluginlib#204]

**Comment by asobhy-qnx** [comment]
@dirk-thomas

**Comment by dirk-thomas** [comment]
@mjcarroll Can this be closed? Does the merged PR need to be backported?

**Comment by mjcarroll** [comment]
Dashing backport: https://github.com/ros/pluginlib/pull/206

**Comment by asobhy-qnx** [comment]
@mjcarroll can you please backport to foxy as well?
