### ISSUE TITLE
OS X has issues compiling with SDK <10.15

### ISSUE THREAD

**Issue by wolfv** [ros/pluginlib#215]
We've ran into problems with MAC OS X deployment target <10.15, as the filesystem API is not generally available before that. 

Specifying 10.15 works, but it's not really desirable. I am also suspecting that there are OGRE build issues because of the 10.15 deployment target pin but I need to investigate that further.

https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=1468&view=logs&j=d8aa8ae6-4ee0-509c-2416-7578dbf33661&t=92bab187-11ce-5b74-46b1-29d1132b53a5&l=1462

**Comment by clalancette** [comment]
We've removed all linking against std::filesystem in this package as of #212.  Since I think that will fix this issue, I'm going to close this out.  Feel free to reopen if I'm mistaken.
