### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by georgiagn** [ros/pluginlib#241]
In order to use this package (which is by default installed with ros-core) in a production release, we need to indicate its license. Could you please add a licence?

**Comment by tfoote** [comment]
The license is called out in the package.xml https://github.com/ros/pluginlib/blob/5fb0f10d2d354aad5d245c806d61dfa8d3863e64/pluginlib/package.xml#L11

And the BSD license is per file so each file has the full header such as: 
https://github.com/ros/pluginlib/blob/5fb0f10d2d354aad5d245c806d61dfa8d3863e64/pluginlib/include/pluginlib/class_desc.h#L4

This should provide full coverage. If there's a file that's missing the header please reopen.
