### ISSUE TITLE
Galactic Documentation error on createInstance

### ISSUE THREAD

**Issue by BrettRD** [ros/pluginlib#247]
the [docs](https://docs.ros2.org/galactic/api/class_loader/classclass__loader_1_1ClassLoader.html#a568ac3fd7f9ef6817fa78df304bb638a) and [comments](https://github.com/ros/pluginlib/blob/galactic/pluginlib/include/pluginlib/class_loader.hpp#L101) refer to a function called `createInstance`, but the function is actually named [`createSharedInstance`](https://github.com/ros/pluginlib/blob/galactic/pluginlib/include/pluginlib/class_loader.hpp#L121)

How can I make a pull request to fix that?

**Comment by clalancette** [comment]
Since Galactic is EOL, and we removed the offending comments anyway, I'm going to go ahead and close this.
