### ISSUE TITLE
Does ros-iron-pluginlib Support Windows 10?

### ISSUE THREAD

**Issue by songyuc** [ros/pluginlib#249]
Hello,

I am interested in using ros-iron-pluginlib for a project and would like to know if it is compatible with Windows 10. I've searched through the existing issues and documentation but couldn't find any information regarding its compatibility with Windows 10.

Could you please confirm if ros-iron-pluginlib is supported on Windows 10? If it is, are there any special installation steps or considerations that I should be aware of?

Thank you for your time and assistance.

**Comment by clalancette** [comment]
> Could you please confirm if ros-iron-pluginlib is supported on Windows 10? If it is, are there any special installation steps or considerations that I should be aware of?

Yes, it is supported as part of our default install.
