### ISSUE TITLE
fails to configure without gtest

### ISSUE THREAD

**Issue by dirk-thomas** [ros/pluginlib#29]
See http://answers.ros.org/question/173255/compiling-ros-to-virtual-nao/
After calling `catkin_add_gtest` the target can only be used if it actually exists since when the user does not have gtest no target is created.

**Comment by esteve** [comment]
Thanks!

**Comment by esteve** [comment]
That's weird, gtest is both a build and run-time dependency for catkin

**Comment by dirk-thomas** [comment]
There are numerous reasons why this can be the case:
- gtest removed after catkin pcakage was installed
- gtest not installed in the first place (on platforms different then Debian)
- ...

So the CMake code should handle this more graceful.

**Comment by vrabaud** [comment]
the weird thing is those instructions worked for us: really, maybe gtest is not part of that VM

**Comment by vrabaud** [comment]
According to the question, gtest was simply not installed. Not sure if you want to close that bug.

**Comment by esteve** [comment]
I've been trying to get ROS installed onto the OpenNAO VM. I updated the wiki with some fixes, but I couldn't get past the rosdep step. Are there any more up to date instructions somewhere? In any case, I'm going add a check for gtest in CMakeLists.txt and skip the test if it's missing, and close this ticket.
