### ISSUE TITLE
Calling function from wrong derived class after loading from pluginlib

### ISSUE THREAD

**Issue by filipmrc** [ros/pluginlib#30]
Programming is not really my strong suit and I really have no idea what went wrong here:

pkg_1::derived_1: 
base_class: pkg_2::derived_2
         init(a,b,c);
         getAllIK(a,b,c);

pkg_2::derived_2: 
base_class: pkg_3::base
         init(a,b,c);
         getAllIK(a,b,c);
         ... a couple more

pkg_3::base:
        init(a,b,c);
        getAllIK(a,b,c);
        ... a couple more

//other_code
static pluginlib::ClassLoader<pkg_name::base> r_model_loader("pkg_3", "pkg_3::base");
basePtr ptr = r_model_loader.createInstance("pkg1::derived_1");

When i call the function init(a,b,c) , the function called is the one in derived_2. When i call getAllIK, the function called is in derived_1 , but it doesn't receive the values from the call and instead gets junk. The calls are identical. Sometimes segfaults happen.

Base is defined in the header base.h , and all of its functions are actually in derived_2. In my code I am loading derived_2 with plugin lib as follows:

I have exported the derived_1 plugin with the base declared as "pkg_name::base" but that didn't help. Does anyone have any idea what might be the problem?

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org and when you do please provide a reproducible example so we know exactly what you're doing and what you're expecting. Guidelines for asking questions can be found at: http://wiki.ros.org/Support
