### ISSUE TITLE
Problem with installation of ROS from source.

### ISSUE THREAD

**Issue by mpkuse** [ros/pluginlib#32]
pluginlib fails to install as I try to install ROS (Hydro) from source code on my Ubuntu 12.04.
I followed this article to install ros from source. http://wiki.ros.org/Installation/Source

 make -j8 -l8 in '/home/eeuser/installation_ros_src_ws/build_isolated/pluginlib'
Linking CXX executable /home/eeuser/installation_ros_src_ws/devel_isolated/pluginlib/lib/pluginlib/plugin_tool
/home/eeuser/installation_ros_src_ws/install_isolated/lib/libclass_loader.so: error: undefined reference to 'pthread_mutexattr_init'
/home/eeuser/installation_ros_src_ws/install_isolated/lib/libclass_loader.so: error: undefined reference to 'pthread_mutexattr_settype'
/home/eeuser/installation_ros_src_ws/install_isolated/lib/libclass_loader.so: error: undefined reference to 'pthread_mutexattr_destroy'
collect2: ld returned 1 exit status
make[2]: **\* [/home/eeuser/installation_ros_src_ws/devel_isolated/pluginlib/lib/pluginlib/plugin_tool] Error 1
make[1]: **\* [CMakeFiles/plugin_tool.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'pluginlib': 
  Command '/home/eeuser/installation_ros_src_ws/install_isolated/env.sh make -j8 -l8' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/eeuser/installation_ros_src_ws/build_isolated/pluginlib && /home/eeuser/installation_ros_src_ws/install_isolated/env.sh make -j8 -l8

Command failed, exiting.

**Comment by mikaelarguedas** [comment]
Hydro being EOL since before this thicket was open I'll close this.
@mpkuse If you encounter this issue for any currently supported ROS distributions, feel free to open another ticket
