### ISSUE TITLE
release createUniqueInstance into indigo

### ISSUE THREAD

**Issue by v4hn** [ros/pluginlib#45]
@mikaelarguedas mentioned in https://github.com/ros/pluginlib/pull/42#issuecomment-248457801 that the new `createUniqueInstance` interface will be released into indigo and jade too.

It would be great to see this happen in the near future!
MoveIt's main development branch (`kinetic-devel`) requires this feature.
In order to use the branch with ROS indigo, currently one has to overlay the /opt/ros/indigo version of `pluginlib` in the workspace.
It is not easy to upgrade many robotic setups, so this kind of cross-versioning is not too uncommon.

**Comment by mikaelarguedas** [comment]
Closing this now that the `createUniqueInstance` interface has been released into [Jade](http://repositories.ros.org/status_page/ros_jade_default.html?q=pluginlib) and [Indigo](http://repositories.ros.org/status_page/ros_indigo_default.html?q=pluginlib). It's currently in the testing repo (shadow-fixed) and will be available in the main repo after the next sync.

**Comment by v4hn** [comment]
Awsome, thanks!
