### ISSUE TITLE
Error loading RosBridge

### ISSUE THREAD

**Issue by MustafaDaoud** [ros/pluginlib#46]
Hi, 
I am trying to install the package in ROS indigo and VREP3_3_2 
when I run VREP, It cann't load the RosBridge

Plugin 'RosBridge': loading...
[rospack] Error: package 'vrep_ros_plugin' not found
[librospack]: error while executing command
terminate called after throwing an instance of 'pluginlib::ClassLoaderException'
  what():  Unable to find package: vrep_ros_plugin
Aborted (core dumped)

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
