### ISSUE TITLE
wrongly assumes package name is package's folder name

### ISSUE THREAD

**Issue by davetcoleman** [ros/pluginlib#6]
in MoveIt there exists packages whose's folder name does not match their package name - ie moveit_ros_visualization is located in the folder moveit_ros/visualization.  pluginlib assumes that your package name is the same as the folder name. it calls ros::package ::getPath(package_name) and makes sure it matches the current package's location. the fix seems to me to be instead of assuming the package name is the folder name containing "package.xml", instead read the located package.xml and get the package name from there

the issue can be found in class_loader_imp.h, function getPackageFromPluginXMLFilePath() here:

> std::string package_path = ros::package ::getPath(package);
> if (path.find(package_path) == 0)  

@isucan

**Comment by davetcoleman** [comment]
though perhaps there should be some thought into whether a package should have a differently named folder. having the same name is much better for clarity

**Comment by mirzashah** [comment]
I can enhance it to look at the package.xml, shouldn't take too long. However, please reconsider renaming your folders to match the package name for consistency with the rest of ROS.

**Comment by davetcoleman** [comment]
i agree with @mirzashah... what do you think @isucan ?

**Comment by isucan** [comment]
@mirzashah knows all the details about pluginlib and class loader. I think the proposed solution is great.

**Comment by davetcoleman** [comment]
@isucan i meant what do you think about "renaming your folders to match the package name for consistency with the rest of ROS"

**Comment by isucan** [comment]
As I understand things, not being tied to folder names is a new feature of the packaging system. So while packages using rosbuild cannot use this feature, I do not see a reason why new packages should not make use of it.

**Comment by tfoote** [comment]
I talked with @mirzashaw We relaxed the requirement that package names be
the same as directory names.  So the logic in pluginlib needs to be
changed.  It looks like he's already patched
it  25788f5ee8008573531589b84fa3f3fa4fd5d5c7

On Tue, Dec 11, 2012 at 12:44 PM, isucan notifications@github.com wrote:

> As I understand things, not being tied to folder names is a new feature of
> the packaging system. So while packages using rosbuild cannot use this
> feature, I do not see a reason why new packages should not make use of it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/pluginlib/issues/6#issuecomment-11262750.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827
