### ISSUE TITLE
tutorial) Wrong code snippet for plugin.xml

### ISSUE THREAD

**Issue by 130s** [ros/pluginlib#7]
http://www.ros.org/wiki/pluginlib/Tutorials/Writing%20and%20Using%20a%20Simple%20Plugin?action=recall&rev=24
As of this revision, choosing `groovy` shows the right content of `plugin.xml` but `fuerte` and `electric` still shows the same. 

Root cause is in the macro's bug, which is issued https://github.com/ros-infrastructure/roswiki/issues/17

**Comment by esteve** [comment]
This seems to be fixed, selecting a ROS distro shows the appropiate plugin.xml file.
